In [1]:
from keras.models import load_model
import cv2
import numpy as np

model = load_model('face_mask_detector_model.h5')

face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')


text_dictionary = {0:"Mask On", 1:"NO MASK"}
color_dictionary = {0:(0, 255, 0), 1:(0, 0, 255)}

def detect(gray, frame):
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
    for (x, y, w, h) in faces:
        roi_gray = gray[y:y+h, x:x+w]
        roi_gray_resized = cv2.resize(roi_gray, (115, 115))
        roi_gray_normalized = roi_gray_resized/255.0
        roi_gray_reshaped = np.reshape(roi_gray_normalized, (1, 115, 115, 1))
        
        prediction = model.predict(roi_gray_reshaped)
        
        print(prediction)
        
        label = np.argmax(prediction, axis = 1)[0]
        
        cv2.rectangle(frame, (x, y), (x+w, y+h), color_dictionary[label] , 2)
        cv2.rectangle(frame, (x, y-40), (x+w, y), color_dictionary[label] , -1)
        cv2.putText(frame, text_dictionary[label], (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 0, 0), 2)
        
    return frame



video_capture = cv2.VideoCapture(0)  #0 for internal webcam
while True:
    _, frame = video_capture.read()  #gets us the last frame of the webcam
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    canvas = detect(gray, frame)
    cv2.imshow('Video', canvas)
    if(cv2.waitKey(1) & 0xff == ord('q')):
        break

video_capture.release()
cv2.destroyAllWindows()

[[5.460409e-07 9.999994e-01]]
[[3.6218069e-06 9.9999642e-01]]
[[1.6811152e-04 9.9983191e-01]]
[[4.6955520e-05 9.9995303e-01]]
[[9.7144955e-05 9.9990284e-01]]
[[9.0065453e-07 9.9999905e-01]]
[[1.4272565e-07 9.9999988e-01]]
[[1.2228915e-05 9.9998772e-01]]
[[8.800840e-06 9.999912e-01]]
[[3.1397035e-06 9.9999690e-01]]
[[2.8559063e-05 9.9997139e-01]]
[[2.0246400e-05 9.9997973e-01]]
[[5.8892078e-05 9.9994111e-01]]
[[8.4482854e-06 9.9999154e-01]]
[[2.8385424e-05 9.9997163e-01]]
[[7.0895940e-06 9.9999297e-01]]
[[9.1274279e-07 9.9999905e-01]]
[[4.492463e-08 1.000000e+00]]
[[2.8185471e-07 9.9999976e-01]]
[[1.629749e-08 1.000000e+00]]
[[4.9897955e-07 9.9999952e-01]]
[[7.3766505e-06 9.9999261e-01]]
[[3.5739794e-07 9.9999964e-01]]
[[4.7619819e-06 9.9999523e-01]]
[[0.00216955 0.99783045]]
[[0.27024218 0.7297578 ]]
[[0.05682281 0.9431772 ]]
[[0.6196004  0.38039953]]
[[0.0727393  0.92726076]]
[[0.04658666 0.9534133 ]]
[[0.04658666 0.9534133 ]]
[[9.9973232e-01 2.6772317e-04]]
[[0.00483001 0.99516994]]


[[0.02302611 0.97697383]]
[[0.85567987 0.14432009]]
[[0.9956274  0.00437264]]
[[0.25882074 0.7411792 ]]
[[0.5512856  0.44871435]]
[[0.36474827 0.63525176]]
[[0.8402474  0.15975265]]
[[0.09293447 0.9070655 ]]
[[0.8035363  0.19646372]]
[[0.9423812 0.0576188]]
[[0.92187166 0.07812829]]
[[0.40724608 0.5927539 ]]
[[0.01020354 0.98979646]]
[[0.0502461 0.9497539]]
[[0.20480639 0.7951936 ]]
[[0.14737754 0.85262245]]
[[0.5278406 0.4721594]]
[[0.04929215 0.95070785]]
[[8.7340176e-04 9.9912661e-01]]
[[2.1527869e-06 9.9999785e-01]]
[[3.2355905e-07 9.9999964e-01]]
[[1.09235415e-07 9.99999881e-01]]
[[2.433643e-06 9.999976e-01]]
[[8.2974964e-07 9.9999917e-01]]
[[3.7920238e-06 9.9999619e-01]]
[[2.2481308e-06 9.9999774e-01]]
[[9.857205e-06 9.999901e-01]]
[[5.7874748e-04 9.9942124e-01]]
[[7.9026740e-06 9.9999213e-01]]
[[1.3642205e-05 9.9998641e-01]]
[[4.9445367e-05 9.9995053e-01]]
[[9.623300e-05 9.999038e-01]]
[[8.5570576e-04 9.9914432e-01]]
[[3.0692297e-04 9.9969316e-01]]
[[0.01847159 0.9815284 ]]
[[9.